name: mdsine21

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.10
  - numpy
  - numba
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn=1.1.3
  - h5py
  - psutil
  - networkx
  - biopython
  - treeswift
  - py2cytoscape
  - tqdm
  - pyqt
  - ete3
  - pip:
    - ./