name: mdsine2

channels:
  - conda-forge
  - bioconda

dependencies:
  - python >=3.7
  - numpy >=1.21
  - numba >=0.56.1
  - pandas >=1.3
  - scipy >=1.7
  - matplotlib >=3.5
  - seaborn >=0.12
  - scikit-learn >=1.2.2
  - h5py >=3.8
  - psutil >=5.9
  - networkx >=2.6
  - biopython >=1.81
  - treeswift >=1.1.37
  - py2cytoscape >=0.7.1
  - tqdm
  - pyqt >=5.15.7
  - ete3 >=3.1.3
  - pip:
    - ./