name: mdsine2

channels:
  - conda-forge
  - bioconda

dependencies:
  - python
  - numpy
  - numba
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn >=1.2.2
  - h5py
  - psutil
  - networkx
  - biopython
  - treeswift
  - py2cytoscape
  - tqdm
  - pyqt
  - ete3
  - pip:
    - ./